services:
    app:
        build: .
        ports:
            - "9090:80"
        environment:
            APP_ENV: local
            APP_KEY: "base64:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
            APP_DEBUG: "true"
            APP_URL: http://localhost:9090
            LOG_CHANNEL: stack
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3360
            DB_DATABASE: homedaily_tubes
            DB_USERNAME: root
            DB_PASSWORD: 1
            CACHE_DRIVER: file
            QUEUE_CONNECTION: sync
            SESSION_DRIVER: file
            SESSION_LIFETIME: 120
        depends_on:
            - db

    db:
        image: mysql:8
        restart: always
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: "secret"
            MYSQL_ROOT_PASSWORD: "rootsecret"
        ports:
            - "3360:3306"
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
